name: auto_abaplint_fix_pr

on:
  pull_request:

concurrency:
  group: auto_abaplint_fix_pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  auto_abaplint_fix_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5

      - name: Run abaplint (auto-fix config)
        uses: abaplint/actions-abaplint@main
        with:
          config: .github/abaplint/auto_abaplint_fix.jsonc
          version: '2.119.14'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
