name: mirror_abap2xlsx

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 1 * *'

permissions:
  contents: read

jobs:
  mirror_abap2xlsx:
    # Origin repo only
    permissions:
      contents: write
      pull-requests: write
    if: github.repository == 'kartefact/zdbuf'

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v5
    - name: run
      run: |
        git clone https://github.com/abap2xlsx/abap2xlsx.git
        rm -rf src/00/01
        mkdir -p src/00/01
        cp -r abap2xlsx/src/* src/00/01/
        rm -rf abap2xlsx
        git status
    - name: Open PR
      uses: peter-evans/create-pull-request@v8
      with:
        title: mirror-abap2xlsx-update
        branch: mirror-abap2xlsx-update
