name: Unit Tests

on:
  pull_request:
    branches: [main]

concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5

      - name: Run abaplint Unit Tests
        uses: abaplint/actions-abaplint@main
        with:
          config: .github/abaplint/test.jsonc
          version: '2.119.14'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
